### PR TITLE
Oizie/feature router params

### PR DESCRIPTION
**Pull request by oizie**
## Description
Added new params to bootstrap to have the onUpdate and onError callbacks.
Added type definitions for this params.

## Motivation and Context
This will allow to specify the params for the router.

## How Has This Been Tested?
This is tested using a flag to see if the callbacks were called. Maybe add sinon in here would be a good thing to do.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [X ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
The original default history is `createBrowserHistory`, but this PR changes it to `createMemoryHistory`. This may or may not be for the better. Care to share your thoughts for this change, @oizie ?

I do like the change where this is imported from "react-router" instead of directly from "history", as that follows upstream documentation more closely.

**Comment by oizie** [comment]
Since there is no createBrowserHistory only browserHistory the only createHistory I could see was this one and createHashHistory. You are right this shouldn't go as it is. Maybe we can just use browserHistory although this doesn't have a way to set the params.

**Comment by remojansen** [comment]
Looks like you need:

```ts
import createBrowserHistory from "history/lib/createBrowserHistory";
```

I found it at https://github.com/ReactTraining/react-router/blob/master/modules/browserHistory.js#L1

I'm not sure about how will this work with TS but I'm sure there is a way.

**Comment by oizie** [comment]
OK I will fix this. I was trying to remove going to history altogether but it seems there is no other way.

**Comment by oizie** [comment]
Done. It's using createBrowserHistory again.

**Comment by remojansen** [comment]
Thanks a lot! I'm planning to do a PR and release tomorrow. The PR will remove the devtools and use the chrome extension instead so the devtols are not included in the production bundles.

**Pull request merged**
